server:
  port: 9000

app:
  version: 1.0.1

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  packages-to-scan: com.example.demo
  paths-to-match: /api/**
  api-docs:
    version: openapi_3_1
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    use-root-path: true