name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradlew Executable
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew bootJar -x test

      - name: Copy build directory to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2200
          source: "./build/*"
          target: "/workspace/test-deploy"
          script: echo "success copy!!!"

      # - name: Stop previous app
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     port: 2200
      #     script: |
      #       port=9000
      #       pid=$(netstat -tlnp | grep ":$port" | awk '{print $7}' | cut -d'/' -f1)
      #       if [ ! -z "$pid" ]; then
      #         kill $pid
      #       fi

      # - name: Deploy to Ubuntu Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     port: 2200
      #     script: |
      #       cd /workspace/git/generate-thumbnail
      #       git pull origin main
      #       java -jar /workspace/git/generate-thumbnail/build/libs/kopring-thumbnail.jar &
